chore: 3.3.x compilation fixes
3.3.x is failing: https://gitlab.com/Northern.tech/Mender/mender/-/pipelines/943410534


```
# github.com/mendersoftware/mender/app
app/auth.go:266:15: undefined: timers
app/auth.go:279:5: undefined: timers
app/auth.go:295:15: undefined: timers
app/auth.go:304:5: undefined: timers
app/auth.go:413:16: undefined: timers
app/auth.go:418:6: undefined: timers
app/auth.go:476:13: undefined: timers
app/auth.go:481:3: undefined: timers
make: *** [Makefile:85: mender] Error 1
```

this commit represents the missing pieces of

838db0eecea41c9b4e0ca9b6a93e72e2e205daff

Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>