chore: required fixes and license update
* moves to ubuntu:18.04 and python 3.9 to escape the:

```
TypeError: required field "lineno" missing from alias
```

Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>