chore: Always use `std::move` instead of just `move`
New versions of clang++ don't like `move` and error with:

  error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]

Ticket: none
Changelog: none
Signed-off-by: Vratislav Podzimek <v.podzimek@mykolab.com>