error: introduce error wrapper type
Introduce error wrapper that should be used internally. The wrapper can
convey information on whether the error is fatal or not.

Signed-off-by: Maciej Borzecki <maciej.borzecki@open-rnd.pl>